version: '3.5'

services:
   consignment:
      restart: always
      build: 
         context: .
         dockerfile: ./shippy-service-consignment/Dockerfile
      depends_on:
         - datastore
         - vessel
      ports:
         - 50051:50051
      environment:
         MICRO_SERVER_ADDRESS: ":50051"
         MICRO_REGISTRY: "mdns"
         DB_HOST: "mongodb://datastore:27017"
   
   vessel:
      restart: always
      build: ./shippy-service-vessel
      ports:
         - 50052:50051
      environment:
         MICRO_SERVER_ADDRESS: ":50051"
         MICRO_REGISTRY: "mdns"
         DB_HOST: "mongodb://datastore:27017"
   
   cli:
      build:
         context: .
         dockerfile: ./shippy-client-consignment/Dockerfile
      environment:
         MICRO_REGISTRY: "mdns"
      depends_on:
         - consignment
   
   datastore:
      image: mongo
      container_name: "datastore"
      environment:
         - MONGO_DATA_DIR=/data/db
         - MONGO_LOG_DIR=/dev/null
      volumes:
         - ./data/db:/data/db
      ports:
         - 27017
      command: mongod --logpath=/dev/null
